/* - eke.js - */
// http://edrndemo.org/portal_javascripts/eke.js?original=1
if(typeof YAHOO=="undefined"){var YAHOO={}}
YAHOO.namespace=function(){var a=arguments,o=null,i,j,d;for(i=0;i<a.length;++i){d=a[i].split(".");o=YAHOO;for(j=(d[0]=="YAHOO")?1:0;j<d.length;++j){o[d[j]]=o[d[j]]||{};o=o[d[j]]}}
return o};YAHOO.log=function(msg,cat,src){var l=YAHOO.widget.Logger;if(l&&l.log){return l.log(msg,cat,src)} else{return false}};YAHOO.extend=function(subc,superc,overrides){var F=function(){};F.prototype=superc.prototype;subc.prototype=new F();subc.prototype.constructor=subc;subc.superclass=superc.prototype;if(superc.prototype.constructor==Object.prototype.constructor){superc.prototype.constructor=superc}
if(overrides){for(var i in overrides){subc.prototype[i]=overrides[i]}}};YAHOO.augment=function(r,s){var rp=r.prototype,sp=s.prototype,a=arguments,i,p;if(a[2]){for(i=2;i<a.length;++i){rp[a[i]]=sp[a[i]]}} else{for(p in sp){if(!rp[p]){rp[p]=sp[p]}}}};YAHOO.namespace("util","widget","example");YAHOO.util.CustomEvent=function(type,oScope,silent,signature){this.type=type;this.scope=oScope||window;this.silent=silent;this.signature=signature||YAHOO.util.CustomEvent.LIST;this.subscribers=[];if(!this.silent){}
var onsubscribeType="_YUICEOnSubscribe";if(type!==onsubscribeType){this.subscribeEvent=new YAHOO.util.CustomEvent(onsubscribeType,this,true)}};YAHOO.util.CustomEvent.LIST=0;YAHOO.util.CustomEvent.FLAT=1;YAHOO.util.CustomEvent.prototype={subscribe: function(fn,obj,override){if(this.subscribeEvent){this.subscribeEvent.fire(fn,obj,override)}
this.subscribers.push(new YAHOO.util.Subscriber(fn,obj,override))},unsubscribe: function(fn,obj){var found=false;for(var i=0,len=this.subscribers.length;i<len;++i){var s=this.subscribers[i];if(s&&s.contains(fn,obj)){this._delete(i);found=true}}
return found},fire: function(){var len=this.subscribers.length;if(!len&&this.silent){return true}
var args=[],ret=true,i;for(i=0;i<arguments.length;++i){args.push(arguments[i])}
var argslength=args.length;if(!this.silent){}
for(i=0;i<len;++i){var s=this.subscribers[i];if(s){if(!this.silent){}
var scope=s.getScope(this.scope);if(this.signature==YAHOO.util.CustomEvent.FLAT){var param=null;if(args.length>0){param=args[0]}
ret=s.fn.call(scope,param,s.obj)} else{ret=s.fn.call(scope,this.type,args,s.obj)}
if(false===ret){if(!this.silent){}
return false}}}
return true},unsubscribeAll: function(){for(var i=0,len=this.subscribers.length;i<len;++i){this._delete(len-1-i)}},_delete: function(index){var s=this.subscribers[index];if(s){delete s.fn;delete s.obj}
this.subscribers.splice(index,1)},toString: function(){return "CustomEvent: "+"'" + this.type  + "', "+"scope: "+this.scope}};YAHOO.util.Subscriber=function(fn,obj,override){this.fn=fn;this.obj=obj||null;this.override=override};YAHOO.util.Subscriber.prototype.getScope=function(defaultScope){if(this.override){if(this.override===true){return this.obj} else{return this.override}}
return defaultScope};YAHOO.util.Subscriber.prototype.contains=function(fn,obj){if(obj){return(this.fn==fn&&this.obj==obj)} else{return(this.fn==fn)}};YAHOO.util.Subscriber.prototype.toString=function(){return "Subscriber { obj: "+(this.obj||"")+", override: "+(this.override||"no")+" }"};if(!YAHOO.util.Event){YAHOO.util.Event=function(){var loadComplete=false;var listeners=[];var unloadListeners=[];var legacyEvents=[];var legacyHandlers=[];var retryCount=0;var onAvailStack=[];var legacyMap=[];var counter=0;return{POLL_RETRYS:200,POLL_INTERVAL:20,EL:0,TYPE:1,FN:2,WFN:3,OBJ:3,ADJ_SCOPE:4,isSafari:(/Safari|Konqueror|KHTML/gi).test(navigator.userAgent),isIE:(!this.isSafari&&!navigator.userAgent.match(/opera/gi)&&navigator.userAgent.match(/msie/gi)),_interval:null,startInterval: function(){if(!this._interval){var self=this;var callback=function(){self._tryPreloadAttach()};this._interval=setInterval(callback,this.POLL_INTERVAL)}},onAvailable: function(p_id,p_fn,p_obj,p_override){onAvailStack.push({id:p_id,fn:p_fn,obj:p_obj,override:p_override,checkReady:false});retryCount=this.POLL_RETRYS;this.startInterval()},onContentReady: function(p_id,p_fn,p_obj,p_override){onAvailStack.push({id:p_id,fn:p_fn,obj:p_obj,override:p_override,checkReady:true});retryCount=this.POLL_RETRYS;this.startInterval()},addListener: function(el,sType,fn,obj,override){if(!fn||!fn.call){return false}
if(this._isValidCollection(el)){var ok=true;for(var i=0,len=el.length;i<len;++i){ok=this.on(el[i],sType,fn,obj,override)&&ok}
return ok} else if(typeof el=="string"){var oEl=this.getEl(el);if(oEl){el=oEl} else{this.onAvailable(el, function(){YAHOO.util.Event.on(el,sType,fn,obj,override)});return true}}
if(!el){return false}
if("unload"==sType&&obj!==this){unloadListeners[unloadListeners.length]=[el,sType,fn,obj,override];return true}
var scope=el;if(override){if(override===true){scope=obj} else{scope=override}}
var wrappedFn=function(e){return fn.call(scope,YAHOO.util.Event.getEvent(e),obj)};var li=[el,sType,fn,wrappedFn,scope];var index=listeners.length;listeners[index]=li;if(this.useLegacyEvent(el,sType)){var legacyIndex=this.getLegacyIndex(el,sType);if(legacyIndex==-1||el!=legacyEvents[legacyIndex][0]){legacyIndex=legacyEvents.length;legacyMap[el.id+sType]=legacyIndex;legacyEvents[legacyIndex]=[el,sType,el["on"+sType]];legacyHandlers[legacyIndex]=[];el["on"+sType]=function(e){YAHOO.util.Event.fireLegacyEvent(YAHOO.util.Event.getEvent(e),legacyIndex)}}
legacyHandlers[legacyIndex].push(li)} else{this._simpleAdd(el,sType,wrappedFn,false)}
return true},fireLegacyEvent: function(e,legacyIndex){var ok=true;var le=legacyHandlers[legacyIndex];for(var i=0,len=le.length;i<len;++i){var li=le[i];if(li&&li[this.WFN]){var scope=li[this.ADJ_SCOPE];var ret=li[this.WFN].call(scope,e);ok=(ok&&ret)}}
return ok},getLegacyIndex: function(el,sType){var key=this.generateId(el)+sType;if(typeof legacyMap[key]=="undefined"){return-1} else{return legacyMap[key]}},useLegacyEvent: function(el,sType){if(!el.addEventListener&&!el.attachEvent){return true} else if(this.isSafari){if("click"==sType||"dblclick"==sType){return true}}
return false},removeListener: function(el,sType,fn){var i,len;if(typeof el=="string"){el=this.getEl(el)} else if(this._isValidCollection(el)){var ok=true;for(i=0,len=el.length;i<len;++i){ok=(this.removeListener(el[i],sType,fn)&&ok)}
return ok}
if(!fn||!fn.call){return this.purgeElement(el,false,sType)}
if("unload"==sType){for(i=0,len=unloadListeners.length;i<len;i++){var li=unloadListeners[i];if(li&&li[0]==el&&li[1]==sType&&li[2]==fn){unloadListeners.splice(i,1);return true}}
return false}
var cacheItem=null;var index=arguments[3];if("undefined"==typeof index){index=this._getCacheIndex(el,sType,fn)}
if(index>=0){cacheItem=listeners[index]}
if(!el||!cacheItem){return false}
if(this.useLegacyEvent(el,sType)){var legacyIndex=this.getLegacyIndex(el,sType);var llist=legacyHandlers[legacyIndex];if(llist){for(i=0,len=llist.length;i<len;++i){li=llist[i];if(li&&li[this.EL]==el&&li[this.TYPE]==sType&&li[this.FN]==fn){llist.splice(i,1);break}}}} else{this._simpleRemove(el,sType,cacheItem[this.WFN],false)}
delete listeners[index][this.WFN];delete listeners[index][this.FN];listeners.splice(index,1);return true},getTarget: function(ev,resolveTextNode){var t=ev.target||ev.srcElement;return this.resolveTextNode(t)},resolveTextNode: function(node){if(node&&3==node.nodeType){return node.parentNode} else{return node}},getPageX: function(ev){var x=ev.pageX;if(!x&&0!==x){x=ev.clientX||0;if(this.isIE){x+=this._getScrollLeft()}}
return x},getPageY: function(ev){var y=ev.pageY;if(!y&&0!==y){y=ev.clientY||0;if(this.isIE){y+=this._getScrollTop()}}
return y},getXY: function(ev){return [this.getPageX(ev),this.getPageY(ev)]},getRelatedTarget: function(ev){var t=ev.relatedTarget;if(!t){if(ev.type=="mouseout"){t=ev.toElement} else if(ev.type=="mouseover"){t=ev.fromElement}}
return this.resolveTextNode(t)},getTime: function(ev){if(!ev.time){var t=new Date().getTime();try{ev.time=t} catch(e){return t}}
return ev.time},stopEvent: function(ev){this.stopPropagation(ev);this.preventDefault(ev)},stopPropagation: function(ev){if(ev.stopPropagation){ev.stopPropagation()} else{ev.cancelBubble=true}},preventDefault: function(ev){if(ev.preventDefault){ev.preventDefault()} else{ev.returnValue=false}},getEvent: function(e){var ev=e||window.event;if(!ev){var c=this.getEvent.caller;while(c){ev=c.arguments[0];if(ev&&Event==ev.constructor){break}
c=c.caller}}
return ev},getCharCode: function(ev){return ev.charCode||ev.keyCode||0},_getCacheIndex: function(el,sType,fn){for(var i=0,len=listeners.length;i<len;++i){var li=listeners[i];if(li&&li[this.FN]==fn&&li[this.EL]==el&&li[this.TYPE]==sType){return i}}
return-1},generateId: function(el){var id=el.id;if(!id){id="yuievtautoid-"+counter;++counter;el.id=id}
return id},_isValidCollection: function(o){return(o&&o.length&&typeof o!="string"&&!o.tagName&&!o.alert&&typeof o[0]!="undefined")},elCache:{},getEl: function(id){return document.getElementById(id)},clearCache: function(){},_load: function(e){loadComplete=true;var EU=YAHOO.util.Event;if(this.isIE){EU._simpleRemove(window,"load",EU._load)}},_tryPreloadAttach: function(){if(this.locked){return false}
this.locked=true;var tryAgain=!loadComplete;if(!tryAgain){tryAgain=(retryCount>0)}
var notAvail=[];for(var i=0,len=onAvailStack.length;i<len ;++i){var item=onAvailStack[i];if(item){var el=this.getEl(item.id);if(el){if(!item.checkReady||loadComplete||el.nextSibling||(document&&document.body)){var scope=el;if(item.override){if(item.override===true){scope=item.obj} else{scope=item.override}}
item.fn.call(scope,item.obj);delete onAvailStack[i]}} else{notAvail.push(item)}}}
retryCount=(notAvail.length===0)?0:retryCount-1;if(tryAgain){this.startInterval()} else{clearInterval(this._interval);this._interval=null}
this.locked=false;return true},purgeElement: function(el,recurse,sType){var elListeners=this.getListeners(el,sType);if(elListeners){for(var i=0,len=elListeners.length;i<len ;++i){var l=elListeners[i];this.removeListener(el,l.type,l.fn)}}
if(recurse&&el&&el.childNodes){for(i=0,len=el.childNodes.length;i<len ;++i){this.purgeElement(el.childNodes[i],recurse,sType)}}},getListeners: function(el,sType){var elListeners=[];if(listeners&&listeners.length>0){for(var i=0,len=listeners.length;i<len ;++i){var l=listeners[i];if(l&&l[this.EL]===el&&(!sType||sType===l[this.TYPE])){elListeners.push({type:l[this.TYPE],fn:l[this.FN],obj:l[this.OBJ],adjust:l[this.ADJ_SCOPE],index:i})}}}
return(elListeners.length)?elListeners:null},_unload: function(e){var EU=YAHOO.util.Event,i,j,l,len,index;for(i=0,len=unloadListeners.length;i<len;++i){l=unloadListeners[i];if(l){var scope=window;if(l[EU.ADJ_SCOPE]){if(l[EU.ADJ_SCOPE]===true){scope=l[EU.OBJ]} else{scope=l[EU.ADJ_SCOPE]}}
l[EU.FN].call(scope,EU.getEvent(e),l[EU.OBJ]);delete unloadListeners[i];l=null;scope=null}}
if(listeners&&listeners.length>0){j=listeners.length;while(j){index=j-1;l=listeners[index];if(l){EU.removeListener(l[EU.EL],l[EU.TYPE],l[EU.FN],index)}
j=j-1}
l=null;EU.clearCache()}
for(i=0,len=legacyEvents.length;i<len;++i){delete legacyEvents[i][0];delete legacyEvents[i]}
EU._simpleRemove(window,"unload",EU._unload)},_getScrollLeft: function(){return this._getScroll()[1]},_getScrollTop: function(){return this._getScroll()[0]},_getScroll: function(){var dd=document.documentElement,db=document.body;if(dd&&(dd.scrollTop||dd.scrollLeft)){return [dd.scrollTop,dd.scrollLeft]} else if(db){return [db.scrollTop,db.scrollLeft]} else{return [0,0]}},_simpleAdd: function(){if(window.addEventListener){return function(el,sType,fn,capture){el.addEventListener(sType,fn,(capture))}} else if(window.attachEvent){return function(el,sType,fn,capture){el.attachEvent("on"+sType,fn)}} else{return function(){}}}(),_simpleRemove: function(){if(window.removeEventListener){return function(el,sType,fn,capture){el.removeEventListener(sType,fn,(capture))}} else if(window.detachEvent){return function(el,sType,fn){el.detachEvent("on"+sType,fn)}} else{return function(){}}}()}}();(function(){var EU=YAHOO.util.Event;EU.on=EU.addListener;if(document&&document.body){EU._load()} else{EU._simpleAdd(window,"load",EU._load)}
EU._simpleAdd(window,"unload",EU._unload);EU._tryPreloadAttach()})()}
YAHOO.util.EventProvider=function(){};YAHOO.util.EventProvider.prototype={__yui_events:null,__yui_subscribers:null,subscribe: function(p_type,p_fn,p_obj,p_override){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){ce.subscribe(p_fn,p_obj,p_override)} else{this.__yui_subscribers=this.__yui_subscribers||{};var subs=this.__yui_subscribers;if(!subs[p_type]){subs[p_type]=[]}
subs[p_type].push({fn:p_fn,obj:p_obj,override:p_override})}},unsubscribe: function(p_type,p_fn,p_obj){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){return ce.unsubscribe(p_fn,p_obj)} else{return false}},createEvent: function(p_type,p_config){this.__yui_events=this.__yui_events||{};var opts=p_config||{};var events=this.__yui_events;if(events[p_type]){} else{var scope=opts.scope||this;var silent=opts.silent||null;var ce=new YAHOO.util.CustomEvent(p_type,scope,silent,YAHOO.util.CustomEvent.FLAT);events[p_type]=ce;if(opts.onSubscribeCallback){ce.subscribeEvent.subscribe(opts.onSubscribeCallback)}
this.__yui_subscribers=this.__yui_subscribers||{};var qs=this.__yui_subscribers[p_type];if(qs){for(var i=0;i<qs.length;++i){ce.subscribe(qs[i].fn,qs[i].obj,qs[i].override)}}}
return events[p_type]},fireEvent: function(p_type,arg1,arg2,etc){this.__yui_events=this.__yui_events||{};var ce=this.__yui_events[p_type];if(ce){var args=[];for(var i=1;i<arguments.length;++i){args.push(arguments[i])}
return ce.fire.apply(ce,args)} else{return null}},hasEvent: function(type){if(this.__yui_events){if(this.__yui_events[type]){return true}}
return false}};YAHOO.widget.TreeView=function(id){if(id){this.init(id)}};YAHOO.widget.TreeView.prototype={id:null,_el:null,_nodes:null,locked:false,_expandAnim:null,_collapseAnim:null,_animCount:0,maxAnim:2,setExpandAnim: function(type){if(YAHOO.widget.TVAnim.isValid(type)){this._expandAnim=type}},setCollapseAnim: function(type){if(YAHOO.widget.TVAnim.isValid(type)){this._collapseAnim=type}},animateExpand: function(el,node){if(this._expandAnim&&this._animCount<this.maxAnim){var tree=this;var a=YAHOO.widget.TVAnim.getAnim(this._expandAnim,el,
function(){tree.expandComplete(node)});if(a){++this._animCount;this.fireEvent("animStart",{"node":node,"type":"expand"});a.animate()}
return true}
return false},animateCollapse: function(el,node){if(this._collapseAnim&&this._animCount<this.maxAnim){var tree=this;var a=YAHOO.widget.TVAnim.getAnim(this._collapseAnim,el,
function(){tree.collapseComplete(node)});if(a){++this._animCount;this.fireEvent("animStart",{"node":node,"type":"collapse"});a.animate()}
return true}
return false},expandComplete: function(node){--this._animCount;this.fireEvent("animComplete",{"node":node,"type":"expand"})},collapseComplete: function(node){--this._animCount;this.fireEvent("animComplete",{"node":node,"type":"collapse"})},init: function(id){this.id=id;if("string"!==typeof id){this._el=id;this.id=this.generateId(id)}
this.createEvent("animStart",this);this.createEvent("animComplete",this);this.createEvent("collapse",this);this.createEvent("expand",this);this._nodes=[];YAHOO.widget.TreeView.trees[this.id]=this;this.root=new YAHOO.widget.RootNode(this)},draw: function(){var html=this.root.getHtml();this.getEl().innerHTML=html;this.firstDraw=false},getEl: function(){if(!this._el){this._el=document.getElementById(this.id)}
return this._el},regNode: function(node){this._nodes[node.index]=node},getRoot: function(){return this.root},setDynamicLoad: function(fnDataLoader,iconMode){this.root.setDynamicLoad(fnDataLoader,iconMode)},expandAll: function(){if(!this.locked){this.root.expandAll()}},collapseAll: function(){if(!this.locked){this.root.collapseAll()}},getNodeByIndex: function(nodeIndex){var n=this._nodes[nodeIndex];return(n)?n:null},getNodeByProperty: function(property,value){for(var i in this._nodes){var n=this._nodes[i];if(n.data&&value==n.data[property]){return n}}
return null},getNodesByProperty: function(property,value){var values=[];for(var i in this._nodes){var n=this._nodes[i];if(n.data&&value==n.data[property]){values.push(n)}}
return(values.length)?values:null},removeNode: function(node,autoRefresh){if(node.isRoot()){return false}
var p=node.parent;if(p.parent){p=p.parent}
this._deleteNode(node);if(autoRefresh&&p&&p.childrenRendered){p.refresh()}
return true},removeChildren: function(node){while(node.children.length){this._deleteNode(node.children[0])}
node.childrenRendered=false;node.dynamicLoadComplete=false;if(node.expanded){node.collapse()} else{node.updateIcon()}},_deleteNode: function(node){this.removeChildren(node);this.popNode(node)},popNode: function(node){var p=node.parent;var a=[];for(var i=0,len=p.children.length;i<len;++i){if(p.children[i]!=node){a[a.length]=p.children[i]}}
p.children=a;p.childrenRendered=false;if(node.previousSibling){node.previousSibling.nextSibling=node.nextSibling}
if(node.nextSibling){node.nextSibling.previousSibling=node.previousSibling}
node.parent=null;node.previousSibling=null;node.nextSibling=null;node.tree=null;delete this._nodes[node.index]},toString: function(){return "TreeView "+this.id},generateId: function(el){var id=el.id;if(!id){id="yui-tv-auto-id-"+YAHOO.widget.TreeView.counter;++YAHOO.widget.TreeView.counter}
return id},onExpand: function(node){},onCollapse: function(node){}};YAHOO.augment(YAHOO.widget.TreeView,YAHOO.util.EventProvider);YAHOO.widget.TreeView.nodeCount=0;YAHOO.widget.TreeView.trees=[];YAHOO.widget.TreeView.counter=0;YAHOO.widget.TreeView.getTree=function(treeId){var t=YAHOO.widget.TreeView.trees[treeId];return(t)?t:null};YAHOO.widget.TreeView.getNode=function(treeId,nodeIndex){var t=YAHOO.widget.TreeView.getTree(treeId);return(t)?t.getNodeByIndex(nodeIndex):null};YAHOO.widget.TreeView.addHandler=function(el,sType,fn){if(el.addEventListener){el.addEventListener(sType,fn,false)} else if(el.attachEvent){el.attachEvent("on"+sType,fn)}};YAHOO.widget.TreeView.removeHandler=function(el,sType,fn){if(el.removeEventListener){el.removeEventListener(sType,fn,false)} else if(el.detachEvent){el.detachEvent("on"+sType,fn)}};YAHOO.widget.TreeView.preload=function(prefix){prefix=prefix||"ygtv";var styles=["tn","tm","tmh","tp","tph","ln","lm","lmh","lp","lph","loading"];var sb=[];for(var i=0;i<styles.length;++i){sb[sb.length]='<span class="'+prefix+styles[i]+'">&#160;</span>'}
var f=document.createElement("div");var s=f.style;s.position="absolute";s.top="-1000px";s.left="-1000px";f.innerHTML=sb.join("");document.body.appendChild(f);YAHOO.widget.TreeView.removeHandler(window,"load",YAHOO.widget.TreeView.preload)};YAHOO.widget.TreeView.addHandler(window,"load",YAHOO.widget.TreeView.preload);YAHOO.widget.Node=function(oData,oParent,expanded){if(oData){this.init(oData,oParent,expanded)}};YAHOO.widget.Node.prototype={index:0,children:null,tree:null,data:null,parent:null,depth:-1,href:null,target:"_self",expanded:false,multiExpand:true,renderHidden:false,childrenRendered:false,dynamicLoadComplete:false,previousSibling:null,nextSibling:null,_dynLoad:false,dataLoader:null,isLoading:false,hasIcon:true,iconMode:0,_type:"Node",init: function(oData,oParent,expanded){this.data=oData;this.children=[];this.index=YAHOO.widget.TreeView.nodeCount;++YAHOO.widget.TreeView.nodeCount;this.expanded=expanded;this.createEvent("parentChange",this);if(oParent){oParent.appendChild(this)}},applyParent: function(parentNode){if(!parentNode){return false}
this.tree=parentNode.tree;this.parent=parentNode;this.depth=parentNode.depth+1;if(!this.href){this.href="javascript:"+this.getToggleLink()}
if(!this.multiExpand){this.multiExpand=parentNode.multiExpand}
this.tree.regNode(this);parentNode.childrenRendered=false;for(var i=0,len=this.children.length;i<len;++i){this.children[i].applyParent(this)}
this.fireEvent("parentChange");return true},appendChild: function(childNode){if(this.hasChildren()){var sib=this.children[this.children.length-1];sib.nextSibling=childNode;childNode.previousSibling=sib}
this.children[this.children.length]=childNode;childNode.applyParent(this);return childNode},appendTo: function(parentNode){return parentNode.appendChild(this)},insertBefore: function(node){var p=node.parent;if(p){if(this.tree){this.tree.popNode(this)}
var refIndex=node.isChildOf(p);p.children.splice(refIndex,0,this);if(node.previousSibling){node.previousSibling.nextSibling=this}
this.previousSibling=node.previousSibling;this.nextSibling=node;node.previousSibling=this;this.applyParent(p)}
return this},insertAfter: function(node){var p=node.parent;if(p){if(this.tree){this.tree.popNode(this)}
var refIndex=node.isChildOf(p);if(!node.nextSibling){return this.appendTo(p)}
p.children.splice(refIndex+1,0,this);node.nextSibling.previousSibling=this;this.previousSibling=node;this.nextSibling=node.nextSibling;node.nextSibling=this;this.applyParent(p)}
return this},isChildOf: function(parentNode){if(parentNode&&parentNode.children){for(var i=0,len=parentNode.children.length;i<len ;++i){if(parentNode.children[i]===this){return i}}}
return-1},getSiblings: function(){return this.parent.children},showChildren: function(){if(!this.tree.animateExpand(this.getChildrenEl(),this)){if(this.hasChildren()){this.getChildrenEl().style.display=""}}},hideChildren: function(){if(!this.tree.animateCollapse(this.getChildrenEl(),this)){this.getChildrenEl().style.display="none"}},getElId: function(){return "ygtv"+this.index},getChildrenElId: function(){return "ygtvc"+this.index},getToggleElId: function(){return "ygtvt"+this.index},getEl: function(){return document.getElementById(this.getElId())},getChildrenEl: function(){return document.getElementById(this.getChildrenElId())},getToggleEl: function(){return document.getElementById(this.getToggleElId())},getToggleLink: function(){return "YAHOO.widget.TreeView.getNode(\'"+this.tree.id+"\',"+this.index+").toggle()"},collapse: function(){if(!this.expanded){return}
var ret=this.tree.onCollapse(this);if(false===ret){return}
ret=this.tree.fireEvent("collapse",this);if(false===ret){return}
if(!this.getEl()){this.expanded=false;return}
this.hideChildren();this.expanded=false;this.updateIcon()},expand: function(){if(this.expanded){return}
var ret=this.tree.onExpand(this);if(false===ret){return}
ret=this.tree.fireEvent("expand",this);if(false===ret){return}
if(!this.getEl()){this.expanded=true;return}
if(!this.childrenRendered){this.getChildrenEl().innerHTML=this.renderChildren()} else{}
this.expanded=true;this.updateIcon();if(this.isLoading){this.expanded=false;return}
if(!this.multiExpand){var sibs=this.getSiblings();for(var i=0;i<sibs.length;++i){if(sibs[i]!=this&&sibs[i].expanded){sibs[i].collapse()}}}
this.showChildren()},updateIcon: function(){if(this.hasIcon){var el=this.getToggleEl();if(el){el.className=this.getStyle()}}},getStyle: function(){if(this.isLoading){return "ygtvloading"} else{var loc=(this.nextSibling)?"t":"l";var type="n";if(this.hasChildren(true)||(this.isDynamic()&&!this.getIconMode())){type=(this.expanded)?"m":"p"}
return "ygtv"+loc+type}},getHoverStyle: function(){var s=this.getStyle();if(this.hasChildren(true)&&!this.isLoading){s+="h"}
return s},expandAll: function(){for(var i=0;i<this.children.length;++i){var c=this.children[i];if(c.isDynamic()){alert("Not supported (lazy load + expand all)");break} else if(!c.multiExpand){alert("Not supported (no multi-expand + expand all)");break} else{c.expand();c.expandAll()}}},collapseAll: function(){for(var i=0;i<this.children.length;++i){this.children[i].collapse();this.children[i].collapseAll()}},setDynamicLoad: function(fnDataLoader,iconMode){if(fnDataLoader){this.dataLoader=fnDataLoader;this._dynLoad=true} else{this.dataLoader=null;this._dynLoad=false}
if(iconMode){this.iconMode=iconMode}},isRoot: function(){return(this==this.tree.root)},isDynamic: function(){var lazy=(!this.isRoot()&&(this._dynLoad||this.tree.root._dynLoad));return lazy},getIconMode: function(){return(this.iconMode||this.tree.root.iconMode)},hasChildren: function(checkForLazyLoad){return(this.children.length>0||(checkForLazyLoad&&this.isDynamic()&&!this.dynamicLoadComplete))},toggle: function(){if(!this.tree.locked&&(this.hasChildren(true)||this.isDynamic())){if(this.expanded){this.collapse()} else{this.expand()}}},getHtml: function(){this.childrenRendered=false;var sb=[];sb[sb.length]='<div class="ygtvitem" id="'+this.getElId()+'">';sb[sb.length]=this.getNodeHtml();sb[sb.length]=this.getChildrenHtml();sb[sb.length]='</div>';return sb.join("")},getChildrenHtml: function(){var sb=[];sb[sb.length]='<div class="ygtvchildren"';sb[sb.length]=' id="'+this.getChildrenElId()+'"';if(!this.expanded){sb[sb.length]=' style="display:none;"'}
sb[sb.length]='>';if((this.hasChildren(true)&&this.expanded)||(this.renderHidden&&!this.isDynamic())){sb[sb.length]=this.renderChildren()}
sb[sb.length]='</div>';return sb.join("")},renderChildren: function(){var node=this;if(this.isDynamic()&&!this.dynamicLoadComplete){this.isLoading=true;this.tree.locked=true;if(this.dataLoader){setTimeout(
function(){node.dataLoader(node,
function(){node.loadComplete()})},10)} else if(this.tree.root.dataLoader){setTimeout(
function(){node.tree.root.dataLoader(node,
function(){node.loadComplete()})},10)} else{return "Error: data loader not found or not specified."}
return ""} else{return this.completeRender()}},completeRender: function(){var sb=[];for(var i=0;i<this.children.length;++i){sb[sb.length]=this.children[i].getHtml()}
this.childrenRendered=true;return sb.join("")},loadComplete: function(){this.getChildrenEl().innerHTML=this.completeRender();this.dynamicLoadComplete=true;this.isLoading=false;this.expand();this.tree.locked=false},getAncestor: function(depth){if(depth>=this.depth||depth<0){return null}
var p=this.parent;while(p.depth>depth){p=p.parent}
return p},getDepthStyle: function(depth){return(this.getAncestor(depth).nextSibling)?"ygtvdepthcell":"ygtvblankdepthcell"},getNodeHtml: function(){return ""},refresh: function(){this.getChildrenEl().innerHTML=this.completeRender();if(this.hasIcon){var el=this.getToggleEl();if(el){el.className=this.getStyle()}}},toString: function(){return "Node ("+this.index+")"}};YAHOO.augment(YAHOO.widget.Node,YAHOO.util.EventProvider);YAHOO.widget.RootNode=function(oTree){this.init(null,null,true);this.tree=oTree};YAHOO.extend(YAHOO.widget.RootNode,YAHOO.widget.Node,{getNodeHtml: function(){return ""},toString: function(){return "RootNode"},loadComplete: function(){this.tree.draw()}});YAHOO.widget.TextNode=function(oData,oParent,expanded){if(oData){this.init(oData,oParent,expanded);this.setUpLabel(oData)}};YAHOO.extend(YAHOO.widget.TextNode,YAHOO.widget.Node,{labelStyle:"ygtvlabel",labelElId:null,label:null,textNodeParentChange: function(){if(this.tree&&!this.tree.hasEvent("labelClick")){this.tree.createEvent("labelClick",this.tree)}},setUpLabel: function(oData){this.textNodeParentChange();this.subscribe("parentChange",this.textNodeParentChange);if(typeof oData=="string"){oData={label:oData}}
this.label=oData.label;if(oData.href){this.href=oData.href}
if(oData.target){this.target=oData.target}
if(oData.style){this.labelStyle=oData.style}
this.labelElId="ygtvlabelel"+this.index},getLabelEl: function(){return document.getElementById(this.labelElId)},getNodeHtml: function(){var sb=[];sb[sb.length]='<table border="0" cellpadding="0" cellspacing="0">';sb[sb.length]='<tr>';for(var i=0;i<this.depth;++i){sb[sb.length]='<td class="'+this.getDepthStyle(i)+'">&#160;</td>'}
var getNode='YAHOO.widget.TreeView.getNode(\''+this.tree.id+'\','+this.index+')';sb[sb.length]='<td';sb[sb.length]=' id="'+this.getToggleElId()+'"';sb[sb.length]=' class="'+this.getStyle()+'"';if(this.hasChildren(true)){sb[sb.length]=' onmouseover="this.className=';sb[sb.length]=getNode+'.getHoverStyle()"';sb[sb.length]=' onmouseout="this.className=';sb[sb.length]=getNode+'.getStyle()"'}
sb[sb.length]=' onclick="javascript:'+this.getToggleLink()+'">';sb[sb.length]='&#160;';sb[sb.length]='</td>';sb[sb.length]='<td>';sb[sb.length]='<a';sb[sb.length]=' id="'+this.labelElId+'"';sb[sb.length]=' class="'+this.labelStyle+'"';sb[sb.length]=' href="'+this.href+'"';sb[sb.length]=' target="'+this.target+'"';sb[sb.length]=' onclick="return '+getNode+'.onLabelClick('+getNode+')"';if(this.hasChildren(true)){sb[sb.length]=' onmouseover="document.getElementById(\'';sb[sb.length]=this.getToggleElId()+'\').className=';sb[sb.length]=getNode+'.getHoverStyle()"';sb[sb.length]=' onmouseout="document.getElementById(\'';sb[sb.length]=this.getToggleElId()+'\').className=';sb[sb.length]=getNode+'.getStyle()"'}
sb[sb.length]=' >';sb[sb.length]=this.label;sb[sb.length]='</a>';sb[sb.length]='</td>';sb[sb.length]='</tr>';sb[sb.length]='</table>';return sb.join("")},onLabelClick: function(me){return me.tree.fireEvent("labelClick",me)},toString: function(){return "TextNode ("+this.index+") "+this.label}});YAHOO.widget.MenuNode=function(oData,oParent,expanded){if(oData){this.init(oData,oParent,expanded);this.setUpLabel(oData)}
this.multiExpand=false};YAHOO.extend(YAHOO.widget.MenuNode,YAHOO.widget.TextNode,{toString: function(){return "MenuNode ("+this.index+") "+this.label}});YAHOO.widget.HTMLNode=function(oData,oParent,expanded,hasIcon){if(oData){this.init(oData,oParent,expanded);this.initContent(oData,hasIcon)}};YAHOO.extend(YAHOO.widget.HTMLNode,YAHOO.widget.Node,{contentStyle:"ygtvhtml",contentElId:null,content:null,initContent: function(oData,hasIcon){if(typeof oData=="string"){oData={html:oData}}
this.html=oData.html;this.contentElId="ygtvcontentel"+this.index;this.hasIcon=hasIcon},getContentEl: function(){return document.getElementById(this.contentElId)},getNodeHtml: function(){var sb=[];sb[sb.length]='<table border="0" cellpadding="0" cellspacing="0">';sb[sb.length]='<tr>';for(var i=0;i<this.depth;++i){sb[sb.length]='<td class="'+this.getDepthStyle(i)+'">&#160;</td>'}
if(this.hasIcon){sb[sb.length]='<td';sb[sb.length]=' id="'+this.getToggleElId()+'"';sb[sb.length]=' class="'+this.getStyle()+'"';sb[sb.length]=' onclick="javascript:'+this.getToggleLink()+'"';if(this.hasChildren(true)){sb[sb.length]=' onmouseover="this.className=';sb[sb.length]='YAHOO.widget.TreeView.getNode(\'';sb[sb.length]=this.tree.id+'\','+this.index+').getHoverStyle()"';sb[sb.length]=' onmouseout="this.className=';sb[sb.length]='YAHOO.widget.TreeView.getNode(\'';sb[sb.length]=this.tree.id+'\','+this.index+').getStyle()"'}
sb[sb.length]='>&#160;</td>'}
sb[sb.length]='<td';sb[sb.length]=' id="'+this.contentElId+'"';sb[sb.length]=' class="'+this.contentStyle+'"';sb[sb.length]=' >';sb[sb.length]=this.html;sb[sb.length]='</td>';sb[sb.length]='</tr>';sb[sb.length]='</table>';return sb.join("")},toString: function(){return "HTMLNode ("+this.index+")"}});YAHOO.widget.TVAnim=function(){return{FADE_IN:"TVFadeIn",FADE_OUT:"TVFadeOut",getAnim: function(type,el,callback){if(YAHOO.widget[type]){return new YAHOO.widget[type](el,callback)} else{return null}},isValid: function(type){return(YAHOO.widget[type])}}}();YAHOO.widget.TVFadeIn=function(el,callback){this.el=el;this.callback=callback};YAHOO.widget.TVFadeIn.prototype={animate: function(){var tvanim=this;var s=this.el.style;s.opacity=0.1;s.filter="alpha(opacity=10)";s.display="";var dur=0.4;var a=new YAHOO.util.Anim(this.el,{opacity:{from:0.1,to:1,unit:""}},dur);a.onComplete.subscribe( function(){tvanim.onComplete()});a.animate()},onComplete: function(){this.callback()},toString: function(){return "TVFadeIn"}};YAHOO.widget.TVFadeOut=function(el,callback){this.el=el;this.callback=callback};YAHOO.widget.TVFadeOut.prototype={animate: function(){var tvanim=this;var dur=0.4;var a=new YAHOO.util.Anim(this.el,{opacity:{from:1,to:0.1,unit:""}},dur);a.onComplete.subscribe( function(){tvanim.onComplete()});a.animate()},onComplete: function(){var s=this.el.style;s.display="none";s.filter="alpha(opacity=100)";this.callback()},toString: function(){return "TVFadeOut"}};
